### ISSUE TITLE
RPC very slow querying a lot of plans

### ISSUE THREAD

**Issue by dimiandre** [sentinel-official/hub#72]
**Describe the bug**
When a lot of plans are present on-chain, this endpoint is very slow https://sentinel-rpc.dimi.sh/plans and could lead in a terrible ux while using the dVPN desktop client

**Expected behavior**
Consider implementing a provider based search like /providers/{address}/plans

**Comment by ironman0x7b2** [comment]
Hi, @dimiandre Thank you for reporting this. Yes, I too feel that GetPlans query takes a long time to process the request and the same applies to other queries which are similar to this. This is because of the nature of KVStores that we are using. And also we can't perform on-chain KVStore index since it takes a lot of space.

We have already implemented provider based search.

**Comment by dimiandre** [comment]
> Hi, @dimiandre Thank you for reporting this. Yes, I too feel that GetPlans query takes a long time to process the request and the same applies to other queries which are similar to this. This is because of the nature of KVStores that we are using. And also we can't perform on-chain KVStore index since it takes a lot of space.
> 
> We have already implemented provider based search.

I see! I'm closing this so, thanks for the explanation!
